=== prasadth16/PrasadTestProjects/XMLproject/com/xml/document/Order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.prasad.thakur/Order"
	xmlns:tns="http://www.prasad.thakur/Order" elementFormDefault="qualified">
	<element name="order" type="tns:ordertype" />
	<complexType name="ordertype">
		<sequence>
			<element name="item-id" type="tns:ID" />
			<element name="order-date" type="date" />
			<element name="category" type="tns:ctgry" />
			<element name="shipping" type="tns:shippingdetail" />
		</sequence>
	</complexType>
	<complexType name="shippingdetail">
		<sequence>
			<element name="shipping-date" type="date" />
			<element name="expected-del-dt" type="date" />
			<element name="shipping-method" type="string" />
			<element name="shipping-address" type="tns:address" />
		</sequence>
	</complexType>
	<complexType name="address">
		<sequence>
			<element name="addressln1" type="string" />
			<element name="addressln2" type="string" />
			<element name="state" type="string" />
			<element name="zip" type="tns:zipcode" />
			<element name="country" type="string" />
		</sequence>
	</complexType>
	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*" />
		</restriction>
	</simpleType>
	<simpleType name="ctgry">
		<restriction base="string">
			<enumeration value="E" />
			<enumeration value="K" />
			<enumeration value="B" />
			<enumeration value="G" />
		</restriction>
	</simpleType>
	<simpleType name="zipcode">
	<restriction base="string">
	<maxLength value="5"/>
	<pattern value="[0-9]*"/>
	</restriction>
	</simpleType>

</schema>

=== prasadth16/PrasadTestProjects/JaxB_prac1/src/XSD/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:order xmlns:tns="http://www.prasad.thakur/Order" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.prasad.thakur/Order Order.xsd ">
  <tns:item-id>123</tns:item-id>
  <tns:order-date>2016-02-24</tns:order-date>
  <tns:category>E</tns:category>
  <tns:shipping>
    <tns:shipping-date>2016-02-25</tns:shipping-date>
    <tns:expected-del-dt>2001-03-01</tns:expected-del-dt>
    <tns:shipping-method>Regular</tns:shipping-method>
    <tns:shipping-address>
      <tns:addressln1>19539 Caravan Drive</tns:addressln1>
      <tns:addressln2>Germantown</tns:addressln2>
      <tns:state>MD</tns:state>
      <tns:zip>20874</tns:zip>
      <tns:country>US</tns:country>
    </tns:shipping-address>
  </tns:shipping>
</tns:order>
